apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp3
  template:
    metadata:
      labels:
        app: myapp3
    spec:
      containers:
      - name: myapp3-container
        image: harshithbanuri/myapp3:latest
        ports:
        - containerPort: 8080  

---

apiVersion: v1
kind: Service
metadata:
  name: myapp3-service
spec:
  selector:
    app: myapp3
  type: NodePort
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 8080  
